### ISSUE TITLE
this file can not run 

### ISSUE THREAD

**Issue by hzlzw2003** [PhilippSalvisberg/docker-oracle12ee#1]
if you add -v ***:/u01/app/oracle  , then  it can not run !
if not  add -v ***:** , it has no database instance  !

so  it is a  trash!

**Comment by PhilippSalvisberg** [comment]
As pointed out in the readme:

The purpose of this image is provide all software components to create Oracle database instances including sample schemas and APEX. The intended use is for other images such as

   * [PhilippSalvisberg/docker-oddgendemo](https://github.com/PhilippSalvisberg/docker-oddgendemo)
   * [PhilippSalvisberg/docker-oddgendemo-cdb](https://github.com/PhilippSalvisberg/docker-oddgendemo-cdb)

Please have a look at the Dockerfile in these projects  for examples how to use this image.

**Comment by hzlzw2003** [comment]
i have a docker oracle11g file! 
it can create database : you map a  path from host , restart it  ! 
this image , can not start , then others is nothing ! 
I have read that article , but it is too dificult to use ! this means it is a trash ! if it c

**Comment by PhilippSalvisberg** [comment]
This image is not designed to be startet, so please do not try.
